[project]
name = "cookbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "async-openai>=0.0.52",
    "openai-agents>=0.2.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
]
